package co.gamep.sliced.services.std.display.logicalspace.core.base;

class SubGeometryBase {
	public var UVData(default,never) : Dynamic;
	public var UVOffset(default,never) : Int;
	public var UVStride(default,never) : Int;
	public var autoDeriveVertexNormals : Bool;
	public var autoDeriveVertexTangents : Bool;
	public var autoGenerateDummyUVs : Bool;
	public var faceNormals(default,never) : Dynamic;
	public var indexData(default,never) : Dynamic;
	public var numTriangles(default,never) : Int;
	public var parentGeometry : Geometry;
	public var scaleU(default,never) : Float;
	public var scaleV(default,never) : Float;
	public var useFaceWeights : Bool;
	public var vertexData(default,never) : Dynamic;
	public var vertexNormalData(default,never) : Dynamic;
	public var vertexNormalOffset(default,never) : Int;
	public var vertexNormalStride(default,never) : Int;
	public var vertexOffset(default,never) : Int;
	public var vertexPositionData(default,never) : Dynamic;
	public var vertexStride(default,never) : Int;
	public var vertexTangentData(default,never) : Dynamic;
	public var vertexTangentOffset(default,never) : Int;
	public var vertexTangentStride(default,never) : Int;
	public function new():Void {super();}}
