package co.gamep.sliced.services.std.display.logicalspace.materials.compilation;

class ShaderCompiler {
	public var UVSource(default,never) : String;
	public var UVTarget(default,never) : String;
	public var alphaPremultiplied : Bool;
	public var animatableAttributes(default,never) : Dynamic;
	public var animateUVs : Bool;
	public var animationTargetRegisters(default,never) : Dynamic;
	public var cameraPositionIndex(default,never) : Int;
	public var commonsDataIndex(default,never) : Int;
	public var diffuseLightSources : Int;
	public var enableLightFallOff : Bool;
	public var forceSeperateMVP : Bool;
	public var fragmentCode(default,never) : String;
	public var fragmentLightCode(default,never) : String;
	public var fragmentPostLightCode(default,never) : String;
	public var lightFragmentConstantIndex(default,never) : Int;
	public var lightProbeDiffuseIndices(default,never) : Dynamic;
	public var lightProbeSpecularIndices(default,never) : Dynamic;
	public var methodSetup : co.gamep.sliced.services.std.display.logicalspace.materials.methods.ShaderMethodSetup;
	public var needUVAnimation(default,never) : Bool;
	public var normalBufferIndex(default,never) : Int;
	public var numDirectionalLights : Int;
	public var numLightProbes : Int;
	public var numPointLights : Int;
	public var numUsedFragmentConstants(default,never) : Int;
	public var numUsedStreams(default,never) : Int;
	public var numUsedTextures(default,never) : Int;
	public var numUsedVaryings(default,never) : Int;
	public var numUsedVertexConstants(default,never) : Int;
	public var preserveAlpha : Bool;
	public var probeWeightsIndex(default,never) : Int;
	public var sceneMatrixIndex(default,never) : Int;
	public var sceneNormalMatrixIndex(default,never) : Int;
	public var secondaryUVBufferIndex(default,never) : Int;
	public var shadedTarget(default,never) : String;
	public var specularLightSources : Int;
	public var tangentBufferIndex(default,never) : Int;
	public var usesNormals(default,never) : Bool;
	public var usingSpecularMethod(default,never) : Bool;
	public var uvBufferIndex(default,never) : Int;
	public var uvTransformIndex(default,never) : Int;
	public var vertexCode(default,never) : String;
	public function new():Void {super();}}
